# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72bf6bdf54fb4c47b56a90ebc18143997abc13155b7c6b9fe8c08327555af1dda0bb156c3b531aaf21f539a0a6c2b903ee14d52a80fc5077fda917e4f40c789f

test:
  secret_key_base: 8161e28c3a8069b678e698ae9febf54b6385b87c3d11f280b078864b396d8582da0989d5bac3204f44b17ba47be99d2aa69a684fdcea722f092222570b7619c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
